"""
 Test for FHIR G10 validation
 @owners: dcarlson nrichardson
 @systemtype: FHIR
 @filedeps: system/layouts/FHIR/*.html, system/layouts/FHIRBundles/*.html, system/layouts/FHIRSearch/*.html, src/fhir.c, include/fhir.h, system/layouts/FHIRProfiles/*.html
"""

from wcunittest import wcElement, wcDBRecord
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

LOGIN_URL = 'https://inferno726.dg-testlab.com/onc_certification_g10'

def main(d, WCURL):
    d.startSection('Set Handle')
    if "zeus-test" in d.driverOptions.baseurl:
        zeustest = "test"
    else:
        zeustest = ""
    wd = d.getWebDriver()
    res = d.miedb.dbQuery("SELECT value FROM system_info WHERE name='HANDLE' LIMIT 1")
    if res:
        res = res.getRes()
    d.setUserData('handle', res[0]['value'])
    d.endSection()

    d.startSection('Set to current day for Inferno testing, not historical')
    d.miedb.dbExec("UPDATE system_settings SET value='1' WHERE module='System' AND section='Login' AND item='New Login style'")
    d.miedb.dbExec("UPDATE system_settings SET value='' WHERE module='WebChart' AND section='Demo' AND item='Demo Date'")

    d.endSection()

    d.startSection('Connect William Hart to Selenium and set up Hart user')
    d.miedb.dbExec("INSERT IGNORE INTO user_patients SET id=8,id_type='user',pat_id=18,role_id=1")
    d.endSection()

    d.startSection('White list the Inferno website')
    d.miedb.dbExec("INSERT IGNORE INTO login_trusts SET allowed_options=1,login_url='https://inferno726.dg-testlab.com/'")
    d.endSection()

    d.startSection('Update all expire dates on users')
    d.miedb.dbExec("update users SET pwd_expire='2050-01-01 00:00:00'")
    d.endSection()

    d.startSection('Make FHIR Launch porlet visible in user and pat layouts for user physician')
    d.miedb.dbExec("INSERT IGNORE INTO user_moveable_layout SET user_id=(SELECT user_id FROM users WHERE username='physician'),module_name='User Portlet',layout_name='FHIR Launch',col=1,row=0,col_order=3")
    d.miedb.dbExec("INSERT IGNORE INTO user_moveable_layout SET user_id=(SELECT user_id FROM users WHERE username='physician'),module_name='Patient Portlet',layout_name='FHIR Launch',col=1,row=0,col_order=3")
    d.endSection()

    d.startSection('Remove bad records')
    d.miedb.dbExec("delete from rxlist_allergylist where agyid_type=2 AND allergy_id=3413")
    d.miedb.dbExec("delete from observations where obs_code=0")
    d.miedb.dbExec("delete from pat_chart_types where pat_id=(SELECT pat_id FROM patients WHERE last_name='selenium') AND chart_type_id!=3")
    d.endSection()

    d.startSection('Set items for bulk')
    d.miedb.dbExec("INSERT INTO observations SET pat_id=55,obs_name='FHIR Scope String',obs_code=IFNULL((SELECT obs_code FROM observation_codes WHERE obs_name='FHIR Scope String'),0),obs_result='launch system/*.read'")
    d.miedb.dbExec("INSERT IGNORE INTO chart_types SET description='FHIR User'")
    d.miedb.dbExec("INSERT IGNORE INTO pat_chart_types SET pat_id=55, chart_type_id=(SELECT chart_type_id FROM chart_types WHERE description='FHIR User')")
    d.endSection()

    d.startSection('Log into system as whart')
    d.setBaseURL('')
    #Navigate to this page that should log the user in
    d.navigate("https://"+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+".dev.webchart.app/?f=logout")
    d.clickElement(xpath="//span[contains(., 'Standard Login')]")
    d.enterFormData('whart123@mieweb.com', id='login_user')
    d.clickElement(name='login_submit')
    d.enterFormData('MIEseltest2025!', id='login_passwd')
    d.clickElement(name='login_submit')
    d.closePopup()
    d.endSection()

    d.startSection('Create a new G10 Test')
    d.screenshot()
    d.navigate(LOGIN_URL)
    d.clickElement(xpath='//a[contains(., "Start Testing")]')
    d.pause(3)
    d.endSection()

    d.startSection('Run Standalone Patient App')
    #Save the current page URL to INFERNO_TEST_URL
    INFERNO_TEST_URL = d.getWebDriver().current_url
    d.clickElement(xpath='//p[contains(., "Standalone Patient App")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.enterFormData('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi/fhir/', id='input0_text', clear=True)
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.enterFormData('ABC123DEF456GHI789J0', id='input5_text', clear=True)
    d.enterFormData(' patient/Person.read', id='input3_text')
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(60)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=1200)
    d.clickElement(xpath='//a[contains(., "Follow this link to authorize with the SMART")]')
    d.pause(3)
    # d.clickElement(xpath="//input[@type='submit' and @value='Continue']")
    # d.pause(3)
    # Check if at least two elements exist
    d.waitFor(d, lambda d: d.getElement(xpath="//input[@id='pat_scope']"), timeout=100)
    d.clickElement(id='pat_scope')
    d.clickElement(name='allow_access')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.screenshot()
    d.endSection()

    d.startSection('Run Limited Access App')
    d.clickElement(xpath='//p[contains(., "Limited Access App")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    wd.refresh()
    d.waitFor(d, lambda d: d.getElement(xpath="//h3[contains(., 'Standalone Patient App - Limited Access')]"), timeout=1200)
    d.pause(3)
    d.clickElement(xpath='//a[contains(., "Follow this link")]')
    d.waitFor(d, lambda d: d.getElement(xpath="//input[@id='pat_scope']"), timeout=100)
    d.clickElement(id='pat_scope')
    d.clickElement(xpath='//li[contains(., "patient/AllergyIntolerance.read")]')
    d.clickElement(xpath='//li[contains(., "patient/CarePlan.read")]')
    d.clickElement(xpath='//li[contains(., "patient/CareTeam.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Device.read")]')
    d.clickElement(xpath='//li[contains(., "patient/DiagnosticReport.read")]')
    d.clickElement(xpath='//li[contains(., "patient/DocumentReference.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Encounter.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Goal.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Immunization.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Location.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Medication.read")]')
    d.clickElement(xpath='//li[contains(., "patient/MedicationRequest.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Organization.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Person.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Practitioner.read")]')
    d.clickElement(xpath='//li[contains(., "patient/PractitionerRole.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Procedure.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Provenance.read")]')
    d.clickElement(name='allow_access')
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.endSection()

    d.startSection('Log into system as physician')
    d.navigate("https://"+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+".dev.webchart.app/?f=logout")
    d.navigate("https://"+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+".dev.webchart.app/")
    d.clickElement(xpath="//span[contains(., 'Standard Login')]")
    d.enterFormData('physician', id='login_user')
    d.clickElement(name='login_submit')
    d.enterFormData('MIEseltest2025!', id='login_passwd')
    d.clickElement(name='login_submit')
    d.closePopup()
    d.endSection()

    d.startSection('Run EHR Practitioner App')
    d.navigate(INFERNO_TEST_URL)
    d.clickElement(xpath='//p[contains(., "EHR Practitioner App")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    eles = d.getElements(id='input0_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi/fhir/')    
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.enterFormData('ABC123DEF456GHI789J0', id='input5_text', clear=True)
    d.enterFormData(' user/Person.read', id='input3_text')
    d.screenshot() 
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.navigate('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi?f=chart&s=pat&pat_id=18')
    d.pause(5)
    d.clickElement(xpath='//a[contains(., "Launch ONC Local Inferno Launch")]')
    d.pause(4)
    d.switchToPopup()
    wd.refresh()
    d.waitFor(d, lambda d: d.getElement(xpath='//a[contains(., "Follow this link to authorize with the SMART server")]'), timeout=15)
    d.clickElement(xpath='//a[contains(., "Follow this link to authorize with the SMART server")]')
    d.waitFor(d, lambda d: d.getElement(xpath="//input[@id='pat_scope']"), timeout=100)
    d.clickElement(name='allow_access')
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.endSection()

    d.startSection('Run Multi-Patient API')
    d.clickElement(xpath='//p[contains(., "Multi-Patient API")]')
    d.pause(3)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(15)
    d.screenshot()
    d.enterFormData('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi/fhir/', id='input0_text', clear=True)
    # Second input1
    eles = d.getElements(id='input1_text')
    d.screenshot()
    if eles and len(eles) > 1:
        d.screenshot()
        eles[1].clear()
        eles[1].send_keys('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi/oauth/token/')
    eles = d.getElements(id='input2_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('system/*.read')
    eles = d.getElements(id='input3_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('ONC-Inferno-Bulk')
    # First input1, because the dumb inferno pages now use the same id for two different inputs, I want to distinguish between them in the test, and not cause
    # warnings by using enterFormData which will say there is more than one input with the same id
    eles = d.getElements(id='input1_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('50')
    eles = d.getElements(id='input2_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('18,49')
    d.clickElement(xpath='//input[@type="radio" and @value="RS384"]/parent::span')    
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.endSection()

    d.startSection('Run Single Patient API')
    d.clickElement(xpath='//p[contains(., "Single Patient API")]')
    d.pause(3)
    eles = d.getElements(id='input2_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('18,27,49')    
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1800)
    d.endSection()

    d.startSection('Log into system as whart')
    d.setBaseURL('')
    #Navigate to this page that should log the user in
    d.navigate("https://"+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+".dev.webchart.app/?f=logout")
    d.clickElement(xpath="//span[contains(., 'Standard Login')]")
    d.enterFormData('whart123@mieweb.com', id='login_user')
    d.clickElement(name='login_submit')
    d.enterFormData('MIEseltest2025!', id='login_passwd')
    d.clickElement(name='login_submit')
    d.closePopup()
    d.endSection()

    d.startSection('Run SMART Public Client Launch')
    d.navigate(INFERNO_TEST_URL)
    wd.refresh()
    d.pause(5)
    d.clickElement(xpath='//p[contains(., "Public Client Launch")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.enterFormData('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi/fhir/', id='input0_text', clear=True)
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=1200)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Follow this link to auth")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()
    d.waitFor(d, lambda d: d.getElement(xpath="//input[@id='pat_scope']"), timeout=100)
    d.clickElement(id='pat_scope')
    d.clickElement(name='allow_access')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.endSection()

    d.startSection('Run Token Revocation')
    wd.refresh()
    d.pause(5)
    d.miedb.dbExec("INSERT INTO oauth_authorization_codes SET authorization_code='1DBBBB856A786D70235971FF5EF74898EB54F83B3D810EC0C809228691772D31D9E57F6695F8080A874CDEB5341E61587999',user_id=8,issue_dt=NOW(),client_id='ONC-Inferno',reauth=1,revoked=1,requested_scope='pat_id/18 launch/patient openid fhirUser offline_access patient/AllergyIntolerance.read patient/Binary.read patient/CapabilityStatement'")
    d.clickElement(xpath='//p[contains(., "Token Revocation")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//input[@type="radio" and @name="token_revocation_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.enterFormData('43420b33-1f43-481d-99c6-6b50f0dee999', id='input0_text', clear=True)      
    eles = d.getElements(id='input1_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('1DBBBB856A786D70235971FF5EF74898EB54F83B3D810EC0C809228691772D31D9E57F6695F8080A874CDEB5341E61587999')    
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=300)
    d.endSection()

    d.startSection('Run Invalid Token Request')
    wd.refresh()
    d.pause(5)
    d.clickElement(xpath='//p[contains(., "Invalid Token Request")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.screenshot()
    d.pause(10)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=1200)
    d.pause(2)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Follow this link to auth")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()   
    d.waitFor(d, lambda d: d.getElement(xpath="//input[@id='pat_scope']"), timeout=100)
    d.clickElement(id='pat_scope')
    d.clickElement(name='allow_access')
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.screenshot()
    d.endSection()

    d.startSection('Run Visual Inspection')
    wd.refresh()
    d.pause(5)
    d.clickElement(xpath='//p[contains(., "Visual Inspection")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//input[@type="radio" and @name="single_patient_registration_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="multiple_patient_registration_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="resource_authorization_gui_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="offline_access_notification_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="refresh_token_period_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="token_validation_support-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="information_accuracy_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="multi_patient_scopes_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="developer_documentation_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="jwks_cache_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="patient_suffix_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="native_refresh_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="public_url_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="refresh_token_refresh_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=300)
    d.endSection()

    d.startSection('Run Invalid AUD Launch')
    wd.refresh()
    d.pause(5)    
    d.clickElement(xpath='//p[contains(., "Invalid AUD Launch")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Attest launch')]"), timeout=1200)
    d.pause(3)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Attest launch")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.endSection()

    d.startSection('Log into system as physician')
    d.navigate("https://"+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+".dev.webchart.app/?f=logout")
    d.navigate("https://"+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+".dev.webchart.app/")
    d.clickElement(xpath="//span[contains(., 'Standard Login')]")
    d.enterFormData('physician', id='login_user')
    d.clickElement(name='login_submit')
    d.enterFormData('MIEseltest2025!', id='login_passwd')
    d.clickElement(name='login_submit')
    d.closePopup()
    d.endSection()

    d.startSection('Run EHR Launch with Patient Scopes')
    d.navigate(INFERNO_TEST_URL)    
    d.clickElement(xpath='//p[contains(., "EHR Launch with Patient Scopes")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.screenshot()
    eles = d.getElements(id='input0_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi/fhir/')    
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.enterFormData('ABC123DEF456GHI789J0', id='input5_text', clear=True)
    d.enterFormData(' user/Person.read', id='input3_text')
    d.screenshot() 
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.navigate('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi?f=chart&s=pat&t=Patient+Summary&v=dashboard&pat_id=18')
    d.pause(5)
    d.clickElement(xpath='//a[contains(., "Launch ONC Local Inferno Launch")]')
    d.pause(4)
    d.switchToPopup()
    wd.refresh()
    d.pause(30)
    d.waitFor(d, lambda d: d.getElement(xpath='//a[contains(., "Follow this link to authorize with the SMART server")]'), timeout=300)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Follow this link to authorize with the SMART server")]')
    # Check if at least two elements exist
    if len(elements) == 1:
        # Click the first element
        elements[0].click()   
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()        
    d.pause(10)
    d.screenshot()
    d.clickElement(name='allow_access')
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=1200)
    d.endSection()

    d.startSection('Final Report')
    wd.refresh()
    d.navigate(INFERNO_TEST_URL)    
    d.pause(5)
    d.clickElement(xpath='//p[contains(., "Report")]')
    d.pause(3)
    d.verifyElementPresent(xpath="//h1[contains(.,'pass')]")
    d.screenshot()
    d.endSection()

    d.setBaseURL('https://'+d.getUserData('handle').replace("wczt", "").replace("wct", "")+zeustest+'.dev.webchart.app/webchart.cgi')


