"""
 Test for FHIR G10 validation on Live FHIR Sandbox
 @owners: dcarlson nrichardson
 No filedeps, only runs weekly for FHIR Certification Purposes, since it is hitting a live system.
"""

from wcunittest import wcElement, wcDBRecord
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

LOGIN_URL = 'https://inferno726.dg-testlab.com/onc_certification_g10'

def main(d, WCURL):
    old_url = d.driverOptions.baseurl
    d.setBaseURL('')
    d.startSection('Log into fhirr4sandbox as whart123')
    webdriver = d.getWebDriver()
    #Navigate to this page that should log the user in
    #d.navigate("https://zeus.med-web.com/webchart/wctpepperson/simpleLogin.cgi?SimpleLogin_Referer=https://fhirr4sandbox.webch.art/webchart.cgi&SimpleLogin_UserName=whart123&SimpleLogin_DomainName=MIEDEVICES-MIE8")
    d.navigate("https://fhirr4sandbox.webch.art/webchart.cgi")
    d.enterFormData('whart123', id='login_user')
    d.clickElement(name='login_submit')
    d.enterFormData('MIEseltest2025!', id='login_passwd')
    d.clickElement(name='login_submit')
    d.endSection()

    d.startSection('Create a new G10 Test')
    d.navigate(LOGIN_URL)
    d.clickElement(xpath='//a[contains(., "Start Testing")]')
    d.pause(3)
    d.endSection()

    d.startSection('Run Standalone Patient App')
    #Save the current page URL to INFERNO_TEST_URL
    INFERNO_TEST_URL = d.getWebDriver().current_url
    d.clickElement(xpath='//p[contains(., "Standalone Patient App")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.enterFormData('https://fhirr4sandbox.webch.art/webchart.cgi/fhir/', id='input0_text', clear=True)
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.enterFormData('ABC123DEF456GHI789J0', id='input5_text', clear=True)
    d.enterFormData(' patient/Person.read', id='input3_text')
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(60)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=300)
    d.clickElement(xpath='//a[contains(., "Follow this link to authorize with the SMART")]')
    d.clickElement(id='pat_scope')
    d.clickElement(name='allow_access')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=300)
    d.screenshot()
    d.endSection()

    d.startSection('Run Limited Access App')
    d.clickElement(xpath='//p[contains(., "Limited Access App")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=300)
    d.clickElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]")
    d.clickElement(id='pat_scope')
    d.clickElement(xpath='//li[contains(., "patient/AllergyIntolerance.read")]')
    d.clickElement(xpath='//li[contains(., "patient/CarePlan.read")]')
    d.clickElement(xpath='//li[contains(., "patient/CareTeam.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Device.read")]')
    d.clickElement(xpath='//li[contains(., "patient/DiagnosticReport.read")]')
    d.clickElement(xpath='//li[contains(., "patient/DocumentReference.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Encounter.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Goal.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Immunization.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Location.read")]')
    d.clickElement(xpath='//li[contains(., "patient/MedicationRequest.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Organization.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Person.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Practitioner.read")]')
    d.clickElement(xpath='//li[contains(., "patient/PractitionerRole.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Procedure.read")]')
    d.clickElement(xpath='//li[contains(., "patient/Provenance.read")]')
    d.screenshot()
    d.clickElement(name='allow_access')
    d.pause(30)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=2000)
    d.screenshot()
    d.endSection()

    d.startSection('Log into fhirr4sandbox as physician')
    webdriver = d.getWebDriver()
    webdriver.execute_script("window.open('https://fhirr4sandbox.webch.art/webchart.cgi/fhir?f=logout')")
    d.switchToPopup()
    #Navigate to this page that should log the user in
    #d.navigate("https://zeus.med-web.com/webchart/wctpepperson/simpleLogin.cgi?SimpleLogin_Referer=https://fhirr4sandbox.webch.art/webchart.cgi&SimpleLogin_UserName=physician&SimpleLogin_DomainName=MIEDEVICES-MIE8")
    d.navigate("https://fhirr4sandbox.webch.art/webchart.cgi")
    d.enterFormData('physician', id='login_user')
    d.clickElement(name='login_submit')
    d.enterFormData('MIEseltest2025!', id='login_passwd')
    d.clickElement(name='login_submit')
    d.closePopup()
    d.endSection()

    d.startSection('Run EHR Practitioner App')
    d.clickElement(xpath='//p[contains(., "EHR Practitioner App")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.enterFormData('ABC123DEF456GHI789J0', id='input5_text', clear=True)
    d.enterFormData(' user/Person.read', id='input3_text')
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.navigate('https://fhirr4sandbox.webch.art/webchart.cgi?func=omniscope')
    d.pause(5)
    d.screenshot()
    d.pause(5)
    d.clickElement(xpath='//a[contains(., "Launch ONC Inferno Launch")]')
    d.pause(10)
    d.switchToPopup()
    d.pause(10)
    d.waitFor(d, lambda d: d.getElement(xpath='//a[contains(., "Follow this link to authorize with the SMART")]'), timeout=60)
    d.clickElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]")
    d.clickElement(xpath="//input[@type='radio' and @value='pat_id/18']")
    d.screenshot()
    d.clickElement(name='allow_access')
    d.pause(30)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.screenshot()
    d.endSection()

    d.startSection('Run Single Patient API')
    d.clickElement(xpath='//p[contains(., "Single Patient API")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(30)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=6000)
    d.endSection()

    d.startSection('Run Multi-Patient API')
    d.clickElement(xpath='//p[contains(., "Multi-Patient API")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.enterFormData('https://fhirr4sandbox.webch.art/webchart.cgi/fhir/', id='input0_text', clear=True)
    # Second input1
    eles = d.getElements(id='input1_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('https://fhirr4sandbox.webch.art/webchart.cgi/oauth/token/')
    eles = d.getElements(id='input2_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('system/*.read')
    eles = d.getElements(id='input3_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('ONC-Inferno-bulk')
    # First input1, because the dumb inferno pages now use the same id for two different inputs, I want to distinguish between them in the test, and not cause
    # warnings by using enterFormData which will say there is more than one input with the same id
    eles = d.getElements(id='input1_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('50')
    eles = d.getElements(id='input2_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('18,49')
    d.clickElement(xpath='//input[@type="radio" and @value="RS384"]/parent::span')    
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(30)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.endSection()

    d.startSection('Run SMART Public Client Launch')
    wd = d.getWebDriver()
    wd.refresh()
    d.pause(30)
    d.clickElement(xpath='//p[contains(., "Public Client Launch")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    eles = d.getElements(id='input0_text')
    if eles and len(eles) > 1:
        eles[0].clear()
        eles[0].send_keys('https://fhirr4sandbox.webch.art/webchart.cgi/fhir/')    
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.screenshot()
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=300)
    d.pause(2)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Follow this link to auth")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()   
    d.pause(20)
    d.clickElement(id='pat_scope')
    d.clickElement(name='allow_access')
    d.pause(30)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.endSection()

    d.startSection('Run Token Revocation')
    wd.refresh()
    d.pause(35)
    d.miedb.dbExec("INSERT INTO oauth_authorization_codes SET authorization_code='1DBBBB856A786D70235971FF5EF74898EB54F83B3D810EC0C809228691772D31D9E57F6695F8080A874CDEB5341E61587999',user_id=8,issue_dt=NOW(),client_id='ONC-Inferno',reauth=1,revoked=1,requested_scope='pat_id/18 launch/patient openid fhirUser offline_access patient/AllergyIntolerance.read patient/Binary.read patient/CapabilityStatement'")
    d.clickElement(xpath='//p[contains(., "Token Revocation")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//input[@type="radio" and @name="token_revocation_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.enterFormData('43420b33-1f43-481d-99c6-6b50f0dee999', id='input0_text', clear=True)      
    eles = d.getElements(id='input1_text')
    if eles and len(eles) > 1:
        eles[1].clear()
        eles[1].send_keys('1DBBBB856A786D70235971FF5EF74898EB54F83B3D810EC0C809228691772D31D9E57F6695F8080A874CDEB5341E61587999')      
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.endSection()

    d.startSection('Run Invalid AUD Launch')
    wd.refresh()
    d.pause(35)    
    d.clickElement(xpath='//p[contains(., "Invalid AUD Launch")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Attest launch')]"), timeout=300)
    d.pause(3)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Attest launch")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.endSection()

    d.startSection('Run SMART Invalid Token Request')
    wd.refresh()
    d.pause(35)
    d.clickElement(xpath='//p[contains(., "Invalid Token Request")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.screenshot()
    d.pause(10)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=300)
    d.pause(2)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Follow this link to auth")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()   
    d.pause(10)
    d.clickElement(id='pat_scope')
    d.clickElement(name='allow_access')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.screenshot()
    d.endSection()

    d.startSection('Run Visual Inspection')
    wd.refresh()
    d.pause(35)
    d.clickElement(xpath='//p[contains(., "Visual Inspection")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.clickElement(xpath='//input[@type="radio" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="multiple_patient_registration_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="resource_authorization_gui_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="offline_access_notification_supported-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="refresh_token_period_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="token_validation_support-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="information_accuracy_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="multi_patient_scopes_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="developer_documentation_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="jwks_cache_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="patient_suffix_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="native_refresh_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="public_url_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//input[@type="radio" and @name="refresh_token_refresh_attestation-radio-buttons-group" and @value="true"]/parent::span')
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(3)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=300)
    d.endSection()

    d.startSection('Run EHR Launch with Patient Scopes')
    wd = d.getWebDriver()
    wd.refresh()
    d.pause(30)
    d.clickElement(xpath='//p[contains(., "EHR Launch with Patient Scopes")]')
    d.pause(3)
    d.clickElement(xpath='//button[contains(., "Run Tests")]')
    d.pause(3)
    d.enterFormData('ONC-Inferno', id='input4_text', clear=True)
    d.enterFormData('ABC123DEF456GHI789J0', id='input5_text', clear=True)
    d.clickElement(xpath='//button[contains(., "Submit")]')
    d.pause(10)
    d.screenshot()
    d.navigate('https://fhirr4sandbox.webch.art/webchart.cgi?func=omniscope')
    d.pause(5)
    d.screenshot()
    d.pause(5)
    d.clickElement(xpath='//a[contains(., "Launch ONC Inferno Launch")]')
    d.pause(4)
    d.switchToPopup()
    d.pause(4)
    d.waitFor(d, lambda d: d.getElement(xpath="//a[contains(., 'Follow this link to authorize with the SMART')]"), timeout=300)
    d.pause(2)
    elements = wd.find_elements(By.XPATH, '//a[contains(., "Follow this link to auth")]')
    # Check if at least two elements exist
    if len(elements) >= 2:
        # Click the second element
        elements[1].click()   
    d.pause(10)
    d.clickElement(xpath="//input[@type='radio' and @value='pat_id/18']")
    d.screenshot()
    d.clickElement(name='allow_access')
    d.pause(30)
    d.wcutils.waitFor(lambda d: d.getElement(xpath='//div[contains(@class, "MuiBox-root css-1tz4gpm")]'), expected=False, timeout=3000)
    d.endSection()    
    
    #return to the test, no matter what has happened
    d.startSection('Final Report')
    d.pause(15)
    d.navigate(INFERNO_TEST_URL) 
    d.clickElement(xpath='//p[contains(., "Report")]')
    d.pause(3) 
    d.verifyElementPresent(xpath="//h1[contains(.,'pass')]")
    d.screenshot()
    d.endSection()

    d.setBaseURL(old_url)
